title: Hello, I'm David,
author: David Hason
email: David.Hason@outlook.com
description: > # this means to ignore newlines until "baseurl:"
I’m based in Sydney, Australia and run a small business CellCo.com in here. When I’m not running and overseeing that, I’m focusing on my true passion right here at Cellco company. I’ve been fortunate to have as a professional freelance data analyst and business owner.
I specialize in artificial intelligence, machine learning, and data visualization, and regularly write about my latest work on my personal blog.
If you’d like to talk data, ask about one of my projects, hire me to consult on a project, or anything else, please feel free to contact me by email.
I’m glad you are here. I plan to talk about …
them: minima

# social links
twitter_username: your-twitter-handle
github_username:  DavidHason

show_excerpts: true # set to false to remove excerpts on the homepage
